import React from 'react';
import { Activity, ShieldAlert, Heart, ExternalLink } from 'lucide-react';

export default function Footer() {
  const currentYear = new Date().getFullYear();

  return (
    <footer className="footer">
      <div className="content-wrapper">
        {/* Prominent Educational & Medical Disclaimer Box */}
        <div className="footer-disclaimer-box">
          <ShieldAlert size={24} />
          <div>
            <div className="disclaimer-title">Medical &amp; Research Disclaimer</div>
            <p className="disclaimer-body">
              This application is intended for educational and research purposes only. It is not a medical diagnostic tool. Always consult a qualified healthcare professional for medical advice, diagnosis, or treatment decisions. Never disregard professional medical counsel based on information or automated predictions generated by this software.
            </p>
          </div>
        </div>

        <div className="footer-top">
          <div>
            <div className="footer-brand">
              <div className="footer-brand-icon">
                <Activity size={20} />
              </div>
              <span>Brain Tumor Detection</span>
            </div>
            <p className="footer-about">
              An open deep learning demonstration combining computer vision and MRI radiology datasets to study automated pattern recognition.
            </p>
          </div>

          <div>
            <h4 className="footer-heading">Navigation</h4>
            <ul className="footer-links">
              <li><a href="#hero" className="footer-link">Home</a></li>
              <li><a href="#detection" className="footer-link">Detection Workspace</a></li>
              <li><a href="#how-it-works" className="footer-link">How It Works</a></li>
              <li><a href="#about" className="footer-link">About Project</a></li>
            </ul>
          </div>

          <div>
            <h4 className="footer-heading">System Info</h4>
            <ul className="footer-links">
              <li className="footer-link">API Target: <code>{import.meta.env.VITE_API_URL || 'http://localhost:5000'}</code></li>
              <li className="footer-link">Protocol: REST / multipart/form-data</li>
              <li className="footer-link">Payload: image field</li>
              <li className="footer-link">Status: Active &amp; Ready</li>
            </ul>
          </div>
        </div>

        <div className="footer-bottom">
          <div>
            &copy; {currentYear} <strong>Brain Tumor Detection | AI &amp; Deep Learning Project</strong>
          </div>
          <div>
            Built with ReactJS, Vite &amp; TensorFlow CNN
          </div>
        </div>
      </div>
    </footer>
  );
}
